- name: Facts demo1
  hosts: localhost
  connection: local
  tasks:
    - name: Print a fact
      ansible.builtin.debug:
        msg: Details are - {{ ansible_distribution, ansible_distribution_version, ansible_os_family, ansible_architecture }}