- name: Sample
  hosts: localhost
  connection: local
  tasks:
    - name: ping
      ansible.builtin.ping:
      register: out

    - name: uptime
      ansible.builtin.shell: uptime
      register: out